version: '3'

services:
    app:
        image: ghcr.io/lara-kube/php:8.4
        container_name: lara-kube-app
        environment:
            - APP_ROLE=app
            - PHP_OPCACHE_ENABLE=1
            - PHP_OPCACHE_CLI=1
            - PHP_OPCACHE_REVALIDATE_FREQ=60
        volumes:
            - .:/var/www/html
        entrypoint: ["/bin/sh", "-c", "chmod +x ./docker/entrypoint.sh && ./docker/entrypoint.sh"]
        depends_on:
            - redis
            - websocket
        networks:
            - lara-kube

    horizon:
        image: ghcr.io/lara-kube/php:8.4
        container_name: lara-kube-horizon
        environment:
            - APP_ROLE=horizon
            - PHP_OPCACHE_ENABLE=1
            - PHP_OPCACHE_CLI=1
            - PHP_OPCACHE_REVALIDATE_FREQ=60
        volumes:
            - .:/var/www/html
        entrypoint: ["/bin/sh", "-c", "chmod +x ./docker/entrypoint.sh && ./docker/entrypoint.sh"]
        depends_on:
            - redis
        networks:
            - lara-kube

    websocket:
        image: ghcr.io/lara-kube/php:8.4
        container_name: lara-kube-websocket
        ports:
            -   "6001:6001"
        environment:
            - APP_ROLE=websocket
            - PHP_OPCACHE_ENABLE=1
            - PHP_OPCACHE_CLI=1
            - PHP_OPCACHE_REVALIDATE_FREQ=60
        volumes:
            - .:/var/www/html
        entrypoint: ["/bin/sh", "-c", "chmod +x ./docker/entrypoint.sh && ./docker/entrypoint.sh"]
        depends_on:
            -   redis
        networks:
            - lara-kube


    redis:
        image: redis:alpine
        container_name: lara-kube-redis
        ports:
            - "6379:6379"
        networks:
            - lara-kube

    nginx:
        image: nginx:alpine
        container_name: lara-kube-nginx
        ports:
            - "8080:80"
            - "8081:81"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/reverb.conf:/etc/nginx/conf.d/reverb.conf
            - .:/var/www/html
        depends_on:
            -   app
        networks:
            - lara-kube

networks:
    lara-kube:
        driver: bridge
